### ISSUE TITLE
Streaming from WIFI Camera

### ISSUE THREAD

**Issue by mariomoureperez** [pedroSG94/RTSP-Server#123]
Hello, I currently have a WIFI camera that I connect to my app and display its content on a SurfaceView.

Is there any way to create an RTSP server to stream the content of the SurfaceView instead of the camera's feed?

App Purpose: Any device on the same network as the smartphone should be able to view what is displayed on my SurfaceView via `rtsp://ip-smartphone/`

Thanks

**Comment by pedroSG94** [comment]
Hello,

Yes, this is possible but no directly your SurfaceView.
You need use RtspServerStream class, create a new VideoSource and bind your library used to render that SurfaceView in the VideoSource.

To do it I recommend you read this related posts (the concept is the same but instead of use an external usb camera library you are using a library that get the stream from a rtsp ip):
https://github.com/pedroSG94/RTSP-Server/issues/121
https://github.com/pedroSG94/RTSP-Server/issues/110

If you need more help I will need know the way to connect that rtsp stream with your SurfaceView

**Comment by mariomoureperez** [comment]
Thank you for the quick response, 

If what you suggested doesn't work, could I stream my smartphone screen instead?

I saw that there is a similar issue, #111, but the example link `https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/displayexample` is no longer available.

**Comment by pedroSG94** [comment]
This is the updated link:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/screen
You only need replace GenericStream with RtspServerStream and use startStream method without url

**Comment by mariomoureperez** [comment]
If the camera I'm using keeps updating the ImageView with Bitmaps, can't I use them for streaming?
What I want to do is create an RTSP server so that any device connecting to the RTSP URL of my Android can view the camera stream.
I'm new to video-related topics, and I don't quite understand how to create the RTSP server and then send the Bitmaps or whatever is used in the library to create the stream.
Could you guide me a bit on how to use your libs for this? Thank you very much!

**Comment by pedroSG94** [comment]
Yes, but the performance will be really bad and you need develop a class for it.
Do you have other way to get video frames from the camera? (not bitmap)

**Comment by mariomoureperez** [comment]
I didn't find anything better. The camera is a FLIR One Edge Wi-Fi, and its SDK works like this.

I'm trying to record the screen, which could work as a last resort. I followed your advice to use RtspServerStream, and I managed to establish a connection between VLC and Android, but the video is black.

Do you know how I can fix this in case I decide to share the screen?
Thank you very much!


```
2025-02-06 16:42:33.796 30416-30486 RtspServer              com.example.rtsp         I  Client connected: 192.168.12.164
2025-02-06 16:42:33.823 30416-30486 RtspServer              com.example.rtsp         I  Waiting client...
2025-02-06 16:42:33.881 30416-30660 CommandsManager         com.example.rtsp         I  OPTIONS rtsp://192.168.12.51:1234 RTSP/1.0
                                                                                                    CSeq: 2
                                                                                                    User-Agent: LibVLC/3.0.21 (LIVE555 Streaming Media v2016.11.28)
2025-02-06 16:42:33.883 30416-30660 Client                  com.example.rtsp         I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 2
                                                                                                    Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
2025-02-06 16:42:36.083 30416-30482 BufferPoolAccessor2.0   com.example.rtsp         D  bufferpool2 0xb400007c14945228 : 5(40960 size) total buffers - 4(32768 size) used buffers - 239/244 (recycle/alloc) - 6/479 (fetch/transfer)
2025-02-06 16:42:37.696 30416-30486 CommandsManager         com.example.rtsp         I  DESCRIBE rtsp://192.168.12.51:1234 RTSP/1.0
                                                                                                    CSeq: 3
                                                                                                    User-Agent: LibVLC/3.0.21 (LIVE555 Streaming Media v2016.11.28)
                                                                                                    Accept: application/sdp
2025-02-06 16:42:37.703 30416-30486 Client                  com.example.rtsp         I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 3
                                                                                                    Content-Length: 445
                                                                                                    Content-Base: rtsp://192.168.12.51:1234/
                                                                                                    Content-Type: application/sdp
                                                                                                    
                                                                                                    v=0
                                                                                                    o=- 0 0 IN IP4 192.168.12.51
                                                                                                    s=Unnamed
                                                                                                    i=N/A
                                                                                                    c=IN IP4 192.168.12.164
                                                                                                    t=0 0
                                                                                                    a=recvonly
                                                                                                    m=video 0 RTP/AVP 96
                                                                                                    a=rtpmap:96 H264/90000
                                                                                                    a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAHqwbGoCgPaagwCCg8IhGoA==,aOpDyw==
                                                                                                    a=control:streamid=0
                                                                                                    m=audio 0 RTP/AVP 97
                                                                                                    a=rtpmap:97 MPEG4-GENERIC/32000/2
                                                                                                    a=fmtp:97 profile-level-id=1; mode=AAC-hbr; config=1290; sizelength=13; indexlength=3; indexdeltalength=3
                                                                                                    a=control:streamid=1
2025-02-06 16:42:37.722 30416-30487 CommandsManager         com.example.rtsp         I  SETUP rtsp://192.168.12.51:1234/streamid=0 RTSP/1.0
                                                                                                    CSeq: 4
                                                                                                    User-Agent: LibVLC/3.0.21 (LIVE555 Streaming Media v2016.11.28)
                                                                                                    Transport: RTP/AVP;unicast;client_port=55740-55741
2025-02-06 16:42:37.727 30416-30487 ServerCommandManager    com.example.rtsp         I  Video ports: [55740, 55741]
2025-02-06 16:42:37.728 30416-30487 ServerCommandManager    com.example.rtsp         I  Video ports: [55740, 55741]
2025-02-06 16:42:37.728 30416-30487 Client                  com.example.rtsp         I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 4
                                                                                                    Content-Length: 0
                                                                                                    Transport: RTP/AVP/UDP;unicast;destination=192.168.12.164;client_port=55740-55741;server_port=5006-5007;mode=play
                                                                                                    Session: 1185d20035702ca
                                                                                                    Cache-Control: no-cache
2025-02-06 16:42:37.743 30416-30485 CommandsManager         com.example.rtsp         I  SETUP rtsp://192.168.12.51:1234/streamid=1 RTSP/1.0
                                                                                                    CSeq: 5
                                                                                                    User-Agent: LibVLC/3.0.21 (LIVE555 Streaming Media v2016.11.28)
                                                                                                    Transport: RTP/AVP;unicast;client_port=55742-55743
                                                                                                    Session: 1185d20035702ca
2025-02-06 16:42:37.747 30416-30485 ServerCommandManager    com.example.rtsp         I  Audio ports: [55742, 55743]
2025-02-06 16:42:37.747 30416-30485 ServerCommandManager    com.example.rtsp         I  Audio ports: [55742, 55743]
2025-02-06 16:42:37.747 30416-30485 Client                  com.example.rtsp         I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 5
                                                                                                    Content-Length: 0
                                                                                                    Transport: RTP/AVP/UDP;unicast;destination=192.168.12.164;client_port=55742-55743;server_port=5004-5005;mode=play
                                                                                                    Session: 1185d20035702ca
                                                                                                    Cache-Control: no-cache
2025-02-06 16:42:37.763 30416-30660 CommandsManager         com.example.rtsp         I  PLAY rtsp://192.168.12.51:1234/ RTSP/1.0
                                                                                                    CSeq: 6
                                                                                                    User-Agent: LibVLC/3.0.21 (LIVE555 Streaming Media v2016.11.28)
                                                                                                    Session: 1185d20035702ca
                                                                                                    Range: npt=0.000-
2025-02-06 16:42:37.765 30416-30660 Client                  com.example.rtsp         I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 6
                                                                                                    Content-Length: 0
                                                                                                    RTP-Info: url=rtsp://192.168.12.51:1234/streamid=0;seq=1;rtptime=0,url=rtsp://192.168.12.51:1234/streamid=1;seq=1;rtptime=0
                                                                                                    Session: 1185d20035702ca
2025-02-06 16:42:37.768 30416-30660 Client                  com.example.rtsp         I  Protocol UDP
2025-02-06 16:42:37.851 30416-30664 RtspSender              com.example.rtsp         I  wrote report
2025-02-06 16:42:37.853 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 532
2025-02-06 16:42:37.856 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 537
2025-02-06 16:42:37.858 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 544
2025-02-06 16:42:37.862 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 513
2025-02-06 16:42:37.866 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 524
2025-02-06 16:42:37.872 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 522
2025-02-06 16:42:37.875 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 518
2025-02-06 16:42:37.879 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 522
2025-02-06 16:42:37.880 30416-30664 BasePacket              com.example.rtsp         I  waiting for keyframe
2025-02-06 16:42:37.919 30416-30664 BasePacket              com.example.rtsp         I  waiting for keyframe
2025-02-06 16:42:37.984 30416-30664 BasePacket              com.example.rtsp         I  waiting for keyframe
2025-02-06 16:42:38.063 30416-30664 BasePacket              com.example.rtsp         I  waiting for keyframe
....
2025-02-06 16:42:42.762 30416-30664 RtspSender              com.example.rtsp         I  wrote Video packet, size 32
2025-02-06 16:42:42.835 30416-30664 RtspSender              com.example.rtsp         I  wrote Video packet, size 32
2025-02-06 16:42:42.847 30416-30722 Client                  com.example.rtsp         E  Unexpected error
                                                                                                    kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
                                                                                                    	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:188)
                                                                                                    	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
                                                                                                    	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2025-02-06 16:42:42.892 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 523
2025-02-06 16:42:42.901 30416-30664 RtspSender              com.example.rtsp         I  wrote Audio packet, size 529
2025-02-06 16:42:42.906 30416-30664 RtspSender              com.example.rtsp         I  wrote Video packet, size 32
2025-02-06 16:42:42.970 30416-30664 RtspSender              com.example.rtsp         I  wrote Video packet, size 32    
....

**Comment by pedroSG94** [comment]
Follow this example:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/screen
Remember declare the Service properly:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/AndroidManifest.xml#L73
GenericStream class and RtspServerStream should be totally reemplazable. The only difference is that using GenericStream you call startStream(endpoint) and with RtspServerStream you use startStream()

**Comment by mariomoureperez** [comment]
This is waht i'm using.
I have the manifest just like yours, but with my packages and the same permissions.

I have this service

```@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
class ScreenService: Service(), ConnectChecker{

    companion object {
        private const val TAG = "DisplayService"
        private const val CHANNEL_ID = "DisplayStreamChannel"
        const val NOTIFY_ID = 123456
        var INSTANCE: ScreenService? = null
    }

    private var notificationManager: NotificationManager? = null
    private lateinit var rtspServerStream: RtspServerStream
    private var mediaProjection: MediaProjection? = null
    private val mediaProjectionManager: MediaProjectionManager by lazy {
        applicationContext.getSystemService(MEDIA_PROJECTION_SERVICE) as MediaProjectionManager
    }
    private var callback: ConnectChecker? = null
    private val width = 640
    private val height = 480
    private val vBitrate = 1200 * 1000
    private var rotation = 0 //0 for landscape or 90 for portrait
    private val sampleRate = 32000
    private val isStereo = true
    private val aBitrate = 128 * 1000
    private var prepared = false
    private var recordPath = ""

    override fun onCreate() {
        super.onCreate()
        Log.i(TAG, "RTP Display service create")
        notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(CHANNEL_ID, CHANNEL_ID, NotificationManager.IMPORTANCE_HIGH)
            notificationManager?.createNotificationChannel(channel)
        }
        rtspServerStream = RtspServerStream(baseContext,1234, this, NoVideoSource(), MicrophoneSource()).apply {
            //This is important to keep a constant fps because media projection only produce fps if the screen change
            getGlInterface().setForceRender(true, 15)
        }

        prepared = try {
            rtspServerStream.prepareVideo(width, height, vBitrate, rotation = rotation) &&
                    rtspServerStream.prepareAudio(sampleRate, isStereo, aBitrate,
                        echoCanceler = true,
                        noiseSuppressor = true
                    )
        } catch (e: IllegalArgumentException) {
            false
        }
        if (prepared) INSTANCE = this
        else System.err.println("Invalid audio or video parameters, prepare failed")


        rtspServerStream.startStream()

        System.err.println("RTSP-Services********"+rtspServerStream.isStreaming)
    }

    private fun keepAliveTrick() {
        val notification = NotificationCompat.Builder(this, CHANNEL_ID)
            .setSilent(true)
            .setOngoing(false)
            .build()
        startForeground(1, notification)
    }

    override fun onBind(p0: Intent?): IBinder? {
        return null
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        Log.i(TAG, "RTP Display service started")
        return START_STICKY
    }

    fun sendIntent(): Intent {
        return mediaProjectionManager.createScreenCaptureIntent()
    }

    fun isStreaming(): Boolean {
        return rtspServerStream.isStreaming
    }

    fun isRecording(): Boolean {
        return rtspServerStream.isRecording
    }

    fun stopStream() {
        if (rtspServerStream.isStreaming) {
            rtspServerStream.stopStream()
            notificationManager?.cancel(NOTIFY_ID)
        }
    }

    fun setCallback(connectChecker: ConnectChecker?) {
        callback = connectChecker
    }

    override fun onDestroy() {
        super.onDestroy()
        Log.i(TAG, "RTP Display service destroy")
        stopStream()
        INSTANCE = null
        //release stream and media projection properly
        rtspServerStream.release()
        mediaProjection?.stop()
        mediaProjection = null
    }

    fun prepareStream(resultCode: Int, data: Intent): Boolean {
        keepAliveTrick()
        stopStream()
        mediaProjection?.stop()
        val mediaProjection = mediaProjectionManager.getMediaProjection(resultCode, data)
        this.mediaProjection = mediaProjection
        val screenSource = ScreenSource(applicationContext, mediaProjection)
        return try {
            //ScreenSource need use always setCameraOrientation(0) because the MediaProjection handle orientation.
            //You also need remove autoHandleOrientation if you are using it.
            //You need to call it after prepareVideo to override the default value.
            rtspServerStream.getGlInterface().setCameraOrientation(0)
            rtspServerStream.changeVideoSource(screenSource)
            toggleAudioSource()
            true
        } catch (ignored: IllegalArgumentException) {
            false
        }
    }

    fun getCurrentAudioSource(): AudioSource = rtspServerStream.audioSource

    fun toggleAudioSource() {

                if (rtspServerStream.audioSource is InternalAudioSource) return
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    mediaProjection?.let { rtspServerStream.changeAudioSource(InternalAudioSource(it)) }
                } else {
                    throw IllegalArgumentException("You need min API 29+")
                }
    }

    fun toggleRecord(state: (RecordController.Status) -> Unit) {
        if (!rtspServerStream.isRecording) {
            val folder = PathUtils.getRecordPath()
            if (!folder.exists()) folder.mkdir()
            val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
            recordPath = "${folder.absolutePath}/${sdf.format(Date())}.mp4"
            rtspServerStream.startRecord(recordPath) { status ->
                if (status == RecordController.Status.RECORDING) {
                    state(RecordController.Status.RECORDING)
                }
            }
            state(RecordController.Status.STARTED)
        } else {
            rtspServerStream.stopRecord()
            state(RecordController.Status.STOPPED)
            PathUtils.updateGallery(this, recordPath)
        }
    }

    fun startStream(endpoint: String) {
        if (!rtspServerStream.isStreaming) rtspServerStream.startStream(endpoint)
    }

    fun startStream() {
        if (!rtspServerStream.isStreaming) rtspServerStream.startStream()
        System.err.println("RTSP*******************"+rtspServerStream.toString())
    }

    override fun onConnectionStarted(url: String) {
        callback?.onConnectionStarted(url)
    }

    override fun onConnectionSuccess() {
        callback?.onConnectionSuccess()
    }

    override fun onNewBitrate(bitrate: Long) {
        callback?.onNewBitrate(bitrate)
    }

    override fun onConnectionFailed(reason: String) {
        callback?.onConnectionFailed(reason)
    }

    override fun onDisconnect() {
        callback?.onDisconnect()
    }

    override fun onAuthError() {
        callback?.onAuthError()
    }

    override fun onAuthSuccess() {
        callback?.onAuthSuccess()
    }

}

```

and this implementation in MainActivity

```
  private val activityResultContract =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
            val data = result.data
            if (data != null && result.resultCode == RESULT_OK) {
                val screenService = ScreenService.INSTANCE
                if (screenService != null) {
                    if (screenService.prepareStream(result.resultCode, data)) {
                        screenService.startStream()
                        System.err.println("*********" + screenService.isStreaming())

                    } else {
                        toast("Prepare stream failed")
                    }
                }
            } else {
                toast("No permissions available")

            }
        }


    private lateinit var permissionHandler: PermissionHandler

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        verifyRequiredPermissions()

///RTSP******************

        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        val screenService = ScreenService.INSTANCE

        if (screenService == null) {
            startService(Intent(this, ScreenService::class.java))
        }

        if (screenService != null) {
            System.err.println("************** ${screenService.isRecording()}")
        }

        val service = ScreenService.INSTANCE
        if (service != null) {
            service.setCallback(this)
            if (!service.isStreaming()) {

                activityResultContract.launch(service.sendIntent())
            } else {
                stopStream()
            }
        }

        if (service != null) {
            System.err.println("************** ${service.isRecording()}")
        }

        ScreenService.INSTANCE?.toggleRecord { state ->

            System.err.println("************** $state")

        }


    }


    private fun stopStream() {
        val screenService = ScreenService.INSTANCE
        screenService?.stopStream()
    }
```

**Comment by mariomoureperez** [comment]
Note: The audio from the smartphone's microphone is being transmitted, but the video appears black.

**Comment by pedroSG94** [comment]
Hello,

I found the problem. First of all remove this line from onCreate method in ScreenService:
```
rtspServerStream.startStream()
```
After that, you need call launch with a bit of delay because the activity need to be totally displayed to load the screen permission modal correctly. I let you a code example in MainActivity:
```
private val activityResultContract =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
            val data = result.data
            if (data != null && result.resultCode == RESULT_OK) {
                val screenService = ScreenService.INSTANCE
                if (screenService != null) {
                    if (screenService.prepareStream(result.resultCode, data)) {
                        screenService.startStream()
                        System.err.println("*********" + screenService.isStreaming())

                    } else {
                        toast("Prepare stream failed")
                    }
                }
            } else {
                toast("No permissions available")

            }
        }


    private lateinit var permissionHandler: PermissionHandler

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        verifyRequiredPermissions()

///RTSP******************

        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        val screenService = ScreenService.INSTANCE

        if (screenService == null) {
            startService(Intent(this, ScreenService::class.java))
        }

        if (screenService != null) {
            System.err.println("************** ${screenService.isRecording()}")
        }

        Handler(Looper.getMainLooper()).postDelayed( {
            val service = ScreenService.INSTANCE
            if (service != null) {
                service.setCallback(this)
                if (!service.isStreaming()) {
                    activityResultContract.launch(service.sendIntent())
                } else {
                    stopStream()
                }
            }
        }, 5000)
    }


    private fun stopStream() {
        val screenService = ScreenService.INSTANCE
        screenService?.stopStream()
    }
```
Ideally you should use a button instead of a postDelayed or find a correct way to fix it

**Comment by mariomoureperez** [comment]
Great, thanks a lot! Now it works, although I can't continue using my app in the background. The buttons from my MainActivity don't appear, but I'll try to fix it on my own. Thanks again!  

Can I set the IP to use in `RTSPStreamServer`? Because it's currently using the WiFi IP, and I want to use the USB IP.

**Comment by pedroSG94** [comment]
Maybe, you can try change this IP to your USB IP:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/server/RtspServer.kt#L111
Try use the app example, change it and test. If all is working fine. I will create a PR to add this feature

**Comment by mariomoureperez** [comment]
Okay, thank you very much for your help and for the library. I'll see what I can do, and if I manage to get it working, I'll let you know.

**Comment by mariomoureperez** [comment]
Hi, do you know why i often have this problem?

```
2025-02-11 11:21:02.767 13922-14151 RtspServer              com.example.rtsp.flir_one_edge         I  Server finished
2025-02-11 11:21:17.464  1713-1902  OplusThermalStats       system_server                        E  Error getting package info: com.example.rtsp.flir_one_edge
2025-02-11 11:21:17.517 13922-16710 RtspServer              com.example.rtsp.flir_one_edge         I  Server started: 192.168.87.3:1234
2025-02-11 11:21:17.517 13922-16710 RtspServer              com.example.rtsp.flir_one_edge         I  Waiting client...
2025-02-11 11:21:28.477 13922-14345 RtspServer              com.example.rtsp.flir_one_edge         I  Client connected: 192.168.87.2
2025-02-11 11:21:28.487 13922-14345 RtspServer              com.example.rtsp.flir_one_edge         I  Waiting client...
2025-02-11 11:21:28.492 13922-16710 Client                  com.example.rtsp.flir_one_edge         I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 2
                                                                                                    Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
2025-02-11 11:21:33.376 13922-16710 Client                  com.example.rtsp.flir_one_edge         E  Client disconnected
                                                                                                    java.io.IOException: Broken pipe
                                                                                                    	at io.ktor.utils.io.CloseToken.getCause(CloseToken.kt:37)
                                                                                                    	at io.ktor.utils.io.ByteChannel.getClosedCause(ByteChannel.kt:55)
                                                                                                    	at io.ktor.utils.io.ByteChannel.getWriteBuffer(ByteChannel.kt:47)
                                                                                                    	at io.ktor.utils.io.ByteWriteChannelOperationsKt.writeStringUtf8(ByteWriteChannelOperations.kt:72)
                                                                                                    	at com.pedro.common.socket.TcpStreamSocket$write$8.invokeSuspend(TcpStreamSocket.kt:77)
                                                                                                    	at com.pedro.common.socket.TcpStreamSocket$write$8.invoke(Unknown Source:8)
                                                                                                    	at com.pedro.common.socket.TcpStreamSocket$write$8.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:53)
                                                                                                    	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
                                                                                                    	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:43)
                                                                                                    	at com.pedro.common.socket.TcpStreamSocket.write(TcpStreamSocket.kt:76)
                                                                                                    	at com.pedro.rtspserver.server.ServerClient$startClient$1.invokeSuspend(ServerClient.kt:73)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                                                                                    Caused by: java.io.IOException: Broken pipe
                                                                                                    	at io.ktor.utils.io.CloseToken.<init>(CloseToken.kt:27)
                                                                                                    	at io.ktor.utils.io.ByteChannel.cancel(ByteChannel.kt:133)
                                                                                                    	at io.ktor.utils.io.ByteWriteChannelOperationsKt.close(ByteWriteChannelOperations.kt:92)
                                                                                                    	at io.ktor.utils.io.ByteReadChannelOperationsKt$reader$job$1.invokeSuspend(ByteReadChannelOperations.kt:302)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) 
                                                                                                    Caused by: java.io.IOException: Broken pipe
                                                                                                    	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
                                                                                                    	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:55)
                                                                                                    	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
                                                                                                    	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
                                                                                                    	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:512)
                                                                                                    	at io.ktor.network.sockets.CIOWriterKt$attachForWritingDirectImpl$1.invokeSuspend$lambda$1(CIOWriter.kt:42)
                                                                                                    	at io.ktor.network.sockets.CIOWriterKt$attachForWritingDirectImpl$1.$r8$lambda$vs7rsq9-NeFqQMYucMENivmAomU(Unknown Source:0)
                                                                                                    	at io.ktor.network.sockets.CIOWriterKt$attachForWritingDirectImpl$1$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                                                                                                    	at io.ktor.utils.io.core.ByteReadPacketExtensions_jvmKt.read(ByteReadPacketExtensions.jvm.kt:30)
                                                                                                    	at io.ktor.network.sockets.CIOWriterKt$attachForWritingDirectImpl$1.invokeSuspend(CIOWriter.kt:75)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) 
2025-02-11 11:21:33.580 13922-14391 RtspServer              com.example.rtsp.flir_one_edge         I  Client connected: 192.168.87.2
2025-02-11 11:21:33.604 13922-14391 RtspServer              com.example.rtsp.flir_one_edge         I  Waiting client...
2025-02-11 11:21:33.610 13922-14391 Client                  com.example.rtsp.flir_one_edge         I  RTSP/1.0 500 Internal Server Error
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 0
```

**Comment by pedroSG94** [comment]
That error (IOException) is not really relevant. Only indicate that the client disconnected forcefully without call shutdown command.
Did you able to connect by USB using a different IP in the line indicated? I need know it to implement the feature

**Comment by mariomoureperez** [comment]
Hello, 

I'm working on it, but something weird is happening. Let me explain:  

1. If I have nothing connected via WiFi, it automatically picks up the USB interface, and it works correctly using the USB IP.  
2. If the WiFi interface is active but I force it to use the USB IP, the server supposedly starts with the USB IP, but no client is able to connect.  

To achieve the second point, I changed this—instead of using a VPN, I set it to USB with the name of my network interface.

```
    private fun getIPAddress(): String {
        val interfaces: List<NetworkInterface> = NetworkInterface.getNetworkInterfaces().toList()
        //val vpnInterfaces = interfaces.filter { it.displayName.contains(VPN_INTERFACE) }
        val usbInterfaces = interfaces.filter { it.displayName.contains(USB_INTERFACE) }
        val address: String by lazy { interfaces.findAddress().firstOrNull() ?: DEFAULT_IP }

        //return address
        return if (usbInterfaces.isNotEmpty()) {
            val usbAddresses = usbInterfaces.findAddress()
            usbAddresses.firstOrNull() ?: address
        } else {
            address
        }
    }
```

**Comment by pedroSG94** [comment]
Hello,

Ok, but that method only report you the IP of your device. The IP could no match the real IP used by the server.

I recommend you find the real USB IP of your device and set that IP in the line I shared you previously to force the socket connect to that IP. The problem is that the server socket is not connected to the IP desired.
The reason it is working fine when you disable Wifi could be because the socket only have an IP to connect (USB IP) and then it is using it.

**Comment by mariomoureperez** [comment]
Hi,

I've tried that, but it doesn't work. For now, we can close this issue as I've managed to do what I wanted, except for the IP part. I fixed it by starting the server before the camera connection, although I don't like it.

Now I'm having transmission issues. It works fine with VLC, but when working with an open-source video server called Kurento, it doesn't work well. I understand that this is no longer your responsibility. Can you tell me where you're defining the video and audio codecs, like H264 for MP4, etc.?
With that, you can close the issue. Thanks a lot for your time!

**Comment by pedroSG94** [comment]
Hello,

I'm not sure if you mean the code where I create the RTSP command or codec configuration.
This is the RTSP command line:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/server/ServerCommandManager.kt#L174
About codec configuration you have to go to the main project.
Video:
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L92
Audio:
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java#L62

**Comment by mariomoureperez** [comment]
Thanks a lot for your time!
