### ISSUE TITLE
When using exoplayer to play rtsp stream, a warning message appears and the picture cannot be rendered.

### ISSUE THREAD

**Issue by pengxiao18** [pedroSG94/RTSP-Server#127]
Warning:

Received RTP packet with unexpected sequence number. Expected: 58451; received: 58458. Dropping packet.
Received RTP packet with unexpected sequence number. Expected: 58471; received: 58499. Dropping packet.
Received RTP packet with unexpected sequence number. Expected: 58819; received: 58822. Dropping packet.
Received RTP packet with unexpected sequence number. Expected: 58835; received: 58863. Dropping packet.
Received RTP packet with unexpected sequence number. Expected: 58876; received: 58892. Dropping packet.

**Comment by pedroSG94** [comment]
Hello,

Can you share a code example to reproduce the error?

**Comment by pengxiao18** [comment]
exoPlayer.setVideoSurface(binding.playView.getHolder().getSurface());
Uri uri = Uri.parse(playerUrl);
exoPlayer.setMediaItem(MediaItem.fromUri(uri));
exoPlayer.prepare();
exoPlayer.play();

**Comment by pengxiao18** [comment]
Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:712)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                          at android.os.Looper.loop(Looper.java:300)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: java.io.IOException: DESCRIBE 401
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspMediaPeriod$InternalListener.onSessionTimelineRequestFailed(RtspMediaPeriod.java:697)
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient.dispatchRtspError(RtspClient.java:334)
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient.access$700(RtspClient.java:76)
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:602)
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:527)
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$androidx-media3-exoplayer-rtsp-RtspClient$MessageListener(RtspClient.java:520)
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                          at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:211) 
                                                                                                          at android.os.Looper.loop(Looper.java:300) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                      Caused by: androidx.media3.exoplayer.rtsp.RtspMediaSource$RtspPlaybackException: DESCRIBE 401
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:604)
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:527) 
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$androidx-media3-exoplayer-rtsp-RtspClient$MessageListener(RtspClient.java:520) 
                                                                                                          at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                          at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                          at android.os.Looper.loopOnce(Looper.java:211) 
                                                                                                          at android.os.Looper.loop(Looper.java:300) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67) 
2024-10-24 18:19:12.135  3529-4823  AppPredict              com.miui.securitycenter.remote       E  click app not fount, pkgName is com.xupx.obslive.client
2024-10-24 18:19:12.962 26152-26152 .obslive.client         com.xupx.obslive.client              E  Invalid ID 0x00000000.

**Comment by pengxiao18** [comment]
E  cSeq not found
2024-10-24 18:20:36.640 31197-9385  CommandsManager         com.obslive.android                  I  
2024-10-24 18:20:36.640 31197-9385  CommandParser           com.obslive.android                  E  cSeq not found
2024-10-24 18:20:36.641 31197-9385  Client                  com.obslive.android                  E  Client disconnected
                                                                                                    java.net.SocketException: Broken pipe
                                                                                                    	at java.net.SocketOutputStream.socketWrite0(Native Method)
                                                                                                    	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
                                                                                                    	at java.net.SocketOutputStream.write(SocketOutputStream.java:156)
                                                                                                    	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
                                                                                                    	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
                                                                                                    	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
                                                                                                    	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
                                                                                                    	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
                                                                                                    	at java.io.BufferedWriter.flush(BufferedWriter.java:257)
                                                                                                    	at com.pedro.rtspserver.server.ServerClient.run(SourceFile:66)

**Comment by pedroSG94** [comment]
Hello,

This was fixed in library version 1.3.4. Check the Readme to know the version that you need implement.
Closing as complete
