### ISSUE TITLE
 E/ServerCommandManager: cSeq not found

### ISSUE THREAD

**Issue by meduar** [pedroSG94/RTSP-Server#17]
I am trying to play rstp, but I got this error: I know the issue is with this "rstpserver" since I am using other sources from ipcameras and it works. So the issue is with this rstp server.

 E/ServerCommandManager: cSeq not found

2020-05-06 16:01:46.739 22855-23519/com.pedro.sample W/Client: New client 192.168.1.14
2020-05-06 16:01:46.756 22855-23519/com.pedro.sample E/ServerCommandManager: cSeq not found
2020-05-06 16:01:46.759 22855-23519/com.pedro.sample E/ServerCommandManager: cSeq not found
2020-05-06 16:01:46.763 22855-23519/com.pedro.sample E/Client: Client disconnected
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtspserver.RtspServer$Client.run(RtspServer.kt:138)

request:
DESCRIBE rtsp://192.168.1.6:1935 RTSP/1.0
User-Agent: WMPlayer/12.00.18362.0778 guid/3300AD50-2C39-46C0-AE0A-DB5E646C29AD
Accept: application/sdp
Accept-Charset: UTF-8, *;q=0.1
X-Accept-Authentication: Negotiate, NTLM, Digest
Accept-Language: en-us, *;q=0.1
X-Accept-Proxy-Authentication: Negotiate, NTLM, Digest
CSeq: 1
Supported: com.microsoft.wm.srvppair, com.microsoft.wm.sswitch, com.microsoft.wm.eosmsg, com.microsoft.wm.fastcache, com.microsoft.wm.locid, com.microsoft.wm.rtp.asf, dlna.announce, dlna.rtx, dlna.rtx-dup, com.microsoft.wm.startupprofile

Second: empty request
third has value
...

First has the content shown above, then the second request is empty then it has value and so on.

Do you know what could be causing this?

**Comment by pedroSG94** [comment]
Are you trying to connect IP camera or other device to push data to this server?
This server only support RTSP players, you can't push data to it (not supported).

In this case, my server response to your camera but your camera obviously don't support this response because my server response like if your camera is a player, for this reason the second request is empty
