### ISSUE TITLE
Multiple client reconnections cause the library to crash

### ISSUE THREAD

**Issue by dukess** [pedroSG94/RTSP-Server#30]
Multiple client reconnections cause the library to crash after about 5-20 minutes of running the program. Reconnections occur approximately every 5 seconds. I can guess that under normal conditions (rare connections/reconnections) this error will not occur.

in short:
```
E/AndroidRuntime: FATAL EXCEPTION: BaseEncoder
    Process: ru.dukess.accesscontrolterminal, PID: 13490
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at com.pedro.rtspserver.RtspServer.sendAudio(RtspServer.kt:229)
        at com.pedro.rtspserver.RtspServerCamera1.getAacDataRtp(RtspServerCamera1.kt:79)
```

bigger log:
```
I/RtspServer: Server started 172.16.190.251:2086
I/Client: New client 192.168.3.175
I/Client: OPTIONS rtsp://172.16.190.251:2086/ RTSP/1.0
    CSeq: 1
    User-Agent: RtspClientSharp
    RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 1
    Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
I/Client: DESCRIBE rtsp://172.16.190.251:2086/ RTSP/1.0
    CSeq: 2
    User-Agent: RtspClientSharp
    Accept: application/sdp
    RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 2
    Content-Length: 463
    Content-Base: 172.16.190.251:2086/
    Content-Type: application/sdp
    
    v=0
    o=- 0 0 IN IP4 172.16.190.251
    s=Unnamed
    i=N/A
    c=IN IP4 192.168.3.175
    t=0 0
    a=recvonly
    m=audio 0 RTP/AVP 97
    a=rtpmap:97 MPEG4-GENERIC/44100/2
    a=fmtp:97 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1210; SizeLength=13; IndexLength=3; IndexDeltaLength=3;
    a=control:trackID=1
    m=video 0 RTP/AVP 96
    a=rtpmap:96 H264/90000
    a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J0IAH41oC0ChoQAAAwABAAADAB4PEHqA,KM4ySA==;
    a=control:trackID=0
E/ServerCommandManager: cSeq not found
E/ServerCommandManager: cSeq not found
    cSeq not found
E/Client: Client disconnected
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtspserver.RtspServer$Client.run(RtspServer.kt:172)
....

I/RtspServer: Server started 172.16.190.251:2086
E/AndroidRuntime: FATAL EXCEPTION: BaseEncoder
    Process: ru.dukess.accesscontrolterminal, PID: 32560
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at com.pedro.rtspserver.RtspServer.sendAudio(RtspServer.kt:229)
        at com.pedro.rtspserver.RtspServerCamera1.getAacDataRtp(RtspServerCamera1.kt:79)
        at com.pedro.rtplibrary.base.Camera1Base.getAacData(Camera1Base.java:818)
        at com.pedro.encoder.audio.AudioEncoder.sendBuffer(AudioEncoder.java:117)
        at com.pedro.encoder.BaseEncoder.processOutput(BaseEncoder.java:175)
        at com.pedro.encoder.BaseEncoder.outputAvailable(BaseEncoder.java:208)
        at com.pedro.encoder.BaseEncoder$2.onOutputBufferAvailable(BaseEncoder.java:227)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1664)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1611)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
I/Client: New client 192.168.3.175
I/Client: OPTIONS rtsp://172.16.190.251:2086/ RTSP/1.0
    CSeq: 1
    User-Agent: RtspClientSharp
    RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 1
    Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
I/Client: DESCRIBE rtsp://172.16.190.251:2086/ RTSP/1.0
    CSeq: 2
    User-Agent: RtspClientSharp
    Accept: application/sdp
I/Client: RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 2
    Content-Length: 463
    Content-Base: 172.16.190.251:2086/
    Content-Type: application/sdp
    
    v=0
    o=- 0 0 IN IP4 172.16.190.251
    s=Unnamed
    i=N/A
    c=IN IP4 192.168.3.175
    t=0 0
    a=recvonly
    m=audio 0 RTP/AVP 97
    a=rtpmap:97 MPEG4-GENERIC/44100/2
    a=fmtp:97 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1210; SizeLength=13; IndexLength=3; IndexDeltaLength=3;
    a=control:trackID=1
    m=video 0 RTP/AVP 96
    a=rtpmap:96 H264/90000
    a=fmtp:96 packetization-mode=1; sprop-parameter-sets=J0IAH41oC0ChoQAAAwABAAADAB4PEHqA,KM4ySA==;
    a=control:trackID=0
E/ServerCommandManager: cSeq not found
E/ServerCommandManager: cSeq not found
E/Client: Client disconnected
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtspserver.RtspServer$Client.run(RtspServer.kt:172)
D/accessControlTerminal: surfaceDestroyed
    RTSP server: stopStream
E/RtspServer: Error
    java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:389)
        at java.net.ServerSocket.implAccept(ServerSocket.java:531)
        at java.net.ServerSocket.accept(ServerSocket.java:499)
        at com.pedro.rtspserver.RtspServer$startServer$1.run(RtspServer.kt:45)
        at java.lang.Thread.run(Thread.java:761)
I/RtspServer: Server finished
I/MicrophoneManager: Microphone stopped
I/VideoEncoder: stopped
I/AudioEncoder: stopped
I/Choreographer: Skipped 57 frames!  The application may be doing too much work on its main thread.


```

**Comment by pedroSG94** [comment]
This seems an error using forEach method to iterate in client list. I will replace it as soon as I can

**Comment by dukess** [comment]
Hi! It is possible that the problem stay deeper: yesterday i added code for automatic activity restarting after crashing and got crash with "Too many open files" error after one hour of running. So maybe problem is that in case of an incorrect connection termination on the client side (and raising an exception), files/streams are still not closed:

```
E/ServerCommandManager: cSeq not found
E/ServerCommandManager: cSeq not found
E/Client: Client disconnected
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtspserver.RtspServer$Client.run(RtspServer.kt:172)
E/IMemory: cannot dup fd=1023, size=1384448, err=0 (Too many open files)
    cannot map BpMemoryHeap (binder=0x7c31a79540), size=1384448, fd=-1 (Bad file descriptor)
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 30372 (Binder:29206_7)

```

**Comment by pedroSG94** [comment]
ConcurrentAccess should be solved in last commit:
https://github.com/pedroSG94/RTSP-Server/commit/0ac569a59ca79c7d7a14998189b23ce33db18b22

**Comment by dukess** [comment]
It's cool! One day under DoS-like requests - work still stable.
