### ISSUE TITLE
SocketException: Connection reset

### ISSUE THREAD

**Issue by dannter** [pedroSG94/RTSP-Server#32]
Hi, I have an special player where I put the rtsp path to play the streaming created by de this app but after a few minutes the connection is broken with no sense, the error is this:  

E/Client: Client disconnected
    java.net.SocketException: Connection reset
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:121)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtspserver.ServerClient.run(ServerClient.kt:57)
E/RtspSender: send error: 
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:149)
        at com.pedro.rtsp.rtp.sockets.RtpSocketTcp.sendFrameTCP(RtpSocketTcp.kt:35)
        at com.pedro.rtsp.rtp.sockets.RtpSocketTcp.sendFrame(RtpSocketTcp.kt:23)
        at com.pedro.rtsp.rtsp.RtspSender$start$$inlined$let$lambda$1.run(RtspSender.kt:118)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/RtspSender: Skipping iteration, frame null
E/RtspServer: Error
    java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:213)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:451)
        at java.net.ServerSocket.implAccept(ServerSocket.java:547)
        at java.net.ServerSocket.accept(ServerSocket.java:515)
        at com.pedro.rtspserver.RtspServer$startServer$1.run(RtspServer.kt:45)
        at java.lang.Thread.run(Thread.java:929)
I/RtspServer: Server finished
I/HwAudioRecordImpl: sendStateChangedIntent, state=1
I/HwAudioRecordImpl: sendStateChangedIntent, state=1
I/MicrophoneManager: Microphone stopped
I/VideoEncoder: stopped
W/ACodec: forcing OMX state to Idle when received shutdown in ExecutingState

could you help me to figure it out?, please

**Comment by dannter** [comment]
After checking log files in my player system, I see this: Videomanager do not support video restream. 
Help please :)

**Comment by pedroSG94** [comment]
Hello,

I need info to reproduce it. 
Which is you special player? Do you have a link to download that player?
Can you tell me what do you means with video restream ?This library don't support it.
