### ISSUE TITLE
Video Encoder issue....Please help...!

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#6]
Hi Pedro...
When I wanted to use RtspServerCamera2 class but after changing all the details with RtspServerCamera1 into RtspServerCamera2 then I got following error 
Please Please Please help.....

This is my log...

    Process: com.pedro.rtpstreamer, PID: 8827
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.setCallback(android.media.MediaCodec$Callback, android.os.Handler)' on a null object reference
        at com.pedro.encoder.video.VideoEncoder.start(VideoEncoder.java:158)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:25)
        at com.pedro.rtplibrary.base.Camera2Base.startEncoders(Camera2Base.java:428)
        at com.pedro.rtplibrary.base.Camera2Base.startStream(Camera2Base.java:419)
        at com.pedro.rtspserver.RtspServerCamera2.startStream(RtspServerCamera2.kt:52)
        at com.pedro.rtpstreamer.Camera2DemoActivity.onClick(Camera2DemoActivity.kt:133)
        at android.view.View.performClick(View.java:7259)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27892)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by pedroSG94** [comment]
I'm looking the error.

**Comment by ankitda30** [comment]
Hi Pedro,
My issue is solved by replacing old Camera2Base.java with latest updated code...
Streaming is started but streaming and recorded video display in landscape format....

**Comment by pedroSG94** [comment]
Are you using SurfaceView or TextureView?
Try replace it with OpenGlView

**Comment by ankitda30** [comment]
I'm using SurfaceView....
I'll try with OpenGlView...
Thanks a lot for supporting....

**Comment by ankitda30** [comment]
> I'm using SurfaceView....
> I'll try with OpenGlView...
> Thanks a lot for supporting....

Thanks It Works now......
