### ISSUE TITLE
RTSP/1.0 400 Bad Request

### ISSUE THREAD

**Issue by 1goresha** [pedroSG94/RTSP-Server#66]
when I tried your sample and turned on RTSP streaming (it worked fine) and I tried to turn on recording, the client loses connection with the server.
writes two errors:
E/CommandsManager: read error
    java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
        at java.net.SocketInputStream.read(SocketInputStream.java:176)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:172)
        at java.io.BufferedReader.readLine(BufferedReader.java:335)
        at java.io.BufferedReader.readLine(BufferedReader.java:400)
        at com.pedro.rtsp.rtsp.commands.CommandsManager.getResponse(CommandsManager.kt:255)
        at com.pedro.rtspserver.ServerCommandManager.getRequest(ServerCommandManager.kt:134)
        at com.pedro.rtspserver.ServerClient.run(ServerClient.kt:46)
I/Client: RTSP/1.0 400 Bad Request
    Server: pedroSG94 Server
    Cseq: 0
E/Client: Client disconnected
    java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:124)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtspserver.ServerClient.run(ServerClient.kt:56)

**Comment by pedroSG94** [comment]
The way to reproduce is:
- Start server like in the example
- Connect a client
- Call startRecord in server -> client is disconnected
Right? I will check it and report you back

**Comment by 1goresha** [comment]
Yes,
More details:
Client is vlc android. When client disconnected these exceptions appear. But server doesn't crush.
I am using wifi direct, but i think it doesn't matter here.

**Comment by pedroSG94** [comment]
Fixed here: https://github.com/pedroSG94/RTSP-Server/commit/a88620ec6e602d7ab8e933ee41593a78d2bce839
Test it and let me know if all is solved.

**Comment by 1goresha** [comment]
I just tested it and it work fine, thank dude, you are awesome!
But i tested this library in rtmp-rtsp-stream-client and there i can not create rtsp-server(vlc can not conenct to server)

**Comment by pedroSG94** [comment]
I don't understand this last one.
What do you mean with "tested this library in rtmp-rtsp-stream-client"?

**Comment by 1goresha** [comment]
I meant that I used RtspServerCamera1 instead of RtspCamera1 in rtmp-rtsp-stream-client and it did not work

**Comment by 1goresha** [comment]
Can i use your library for clear rtp(not trsp) streaming? And how, can you direct me to the answer, please?
It is very interisting for me
