### ISSUE TITLE
The demo not working....!

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#7]
Hi Pedro...

After running above updated demo 

==================================================================

Error 1 :- When clicked on Start Server it shows 
Log :- 
2020-03-20 11:05:31.686 13582-14237/com.pedro.sample E/ServerCommandManager: cSeq not found
2020-03-20 11:05:31.687 13582-14237/com.pedro.sample E/Client: Client disconnected
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtspserver.RtspServer$Client.run(RtspServer.kt:137)
==================================================================
Error 2 :- When I Clicked on Start Record then it shows

EACCSS permission denied even when I Already checked all permissions as granted...

Please help.....

**Comment by pedroSG94** [comment]
First error is controlled by library no a crash. This only means that client closed connection. 
In your case cSeq is not send. Maybe you recived a malformed rtsp command

Second error could be because you are recording in a external card or a folder without access (like system folder). You will get this error if you try write anything in that folder so this isn't a library error. You should Google it to find a better response.

**Comment by kuochsia** [comment]
Hi Pedro,

I'm trying your the server as well and I've got the same first error: cSeq not found
I'm using an S8 to run the app and VLC as player, I also tried with Gstreamer but getting the same error..
Here the RTSP logs, this might help :

2020-03-20 11:39:43.814 20530-20941/com.pedro.sample I/Client: OPTIONS rtsp://192.168.1.20:1935/ RTSP/1.0
    CSeq: 1
    User-Agent: GStreamer/1.14.4
    User-Agent: RealMedia Player Version 6.0.9.1235 (linux-2.0-libc6-i386-gcc2.95)
    ClientChallenge: 9e26d33f2984236010ef6253fb1887f7
    CompanyID: KnKV4M4I/B2FjJ1TToLycw==
    GUID: 00000000-0000-0000-0000-000000000000
    RegionData: 0
    PlayerStarttime: [28/03/2003:22:50:23 00:00]
    ClientID: Linux_2.4_6.0.9.1235_play32_RN01_EN_586
    Date: Fri, 20 Mar 2020 10:39:42 GMT
2020-03-20 11:39:43.814 20530-20941/com.pedro.sample I/Client: RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 1
    Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
2020-03-20 11:39:43.826 20530-20941/com.pedro.sample I/Client: DESCRIBE rtsp://192.168.1.20:1935/ RTSP/1.0
    CSeq: 2
    User-Agent: GStreamer/1.14.4
    Accept: application/sdp
    Date: Fri, 20 Mar 2020 10:39:42 GMT
2020-03-20 11:39:43.827 20530-20941/com.pedro.sample I/Client: RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 2
    Content-Length: 440
    Content-Base: 192.168.1.20:1935/
    Content-Type: application/sdp
    
    v=0
    o=- 0 0 IN IP4 192.168.1.20
    s=Unnamed
    i=N/A
    c=IN IP4 192.168.1.29
    t=0 0
    a=recvonly
    m=audio 0 RTP/AVP 96
    a=rtpmap:96 MPEG4-GENERIC/32000/2
    a=fmtp:96 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1290; SizeLength=13; IndexLength=3; IndexDeltaLength=3;
    a=control:trackID=0
    m=video 0 RTP/AVP 96
    a=rtpmap:96 H264/90000
    a=fmtp:96 packetization-mode=1;sprop-parameter-sets=Z0IAHtoHgUZA,aM4NiA==;
    a=control:trackID=1
2020-03-20 11:39:43.844 20530-20941/com.pedro.sample I/Client: SETUP 192.168.1.20:1935/trackID=0 RTSP/1.0
    CSeq: 3
    User-Agent: GStreamer/1.14.4
    Transport: RTP/AVP;unicast;client_port=57854-57855
    Date: Fri, 20 Mar 2020 10:39:42 GMT
2020-03-20 11:39:43.845 20530-20941/com.pedro.sample I/Client: RTSP/1.0 500 Internal Server Error
    Server: pedroSG94 Server
    Cseq: 3
2020-03-20 11:39:43.907 20530-20941/com.pedro.sample E/ServerCommandManager: cSeq not found

**Comment by pedroSG94** [comment]
Can you write a log of request string here?:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServer.kt#L133
I need know string send by client.

**Comment by pedroSG94** [comment]
Internal error is fixed now:
https://github.com/pedroSG94/RTSP-Server/commit/710ab7ef1fac5c79933681ae71e1de49d5e56e52

**Comment by ankitda30** [comment]
Thank you....Very Much.....

**Comment by kuochsia** [comment]
Thank you very much!
