### ISSUE TITLE
Recording keeps stops..... Please Help.....!

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#8]
Hi Pedro,
The above application is working smoothly but I'm facing issues when I click on start streaming video streams well on VLC player but while streaming when I Click on the Start Record then I got the following error....Please help...

Log.....

2020-03-21 12:29:04.140 13398-13609/com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.pedro.rtpstreamer, PID: 13398
    java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:109)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
        at java.net.ServerSocket.bind(ServerSocket.java:377)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at java.net.ServerSocket.<init>(ServerSocket.java:128)
        at com.pedro.rtspserver.RtspServer$startServer$1.run(RtspServer.kt:46)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Linux.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:75)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:75)

**Comment by pedroSG94** [comment]
I dont know reason and I can't reproduce it.
Can you try test with this solution and let me know if you fixed it?:
https://stackoverflow.com/questions/24615704/socket-eaddrinuse-address-already-in-use
